name: Manual test
on:
  workflow_dispatch:
    inputs:
      token:
        description: token to ssh
        type: string
        required: true
      sleepTime:
        description: sleep time
        type: string
      preferredRun:
        description: preferred run
        type: choice
        default: full
        options:
          - full
          - partial


jobs:
  get_workflow_result:
    runs-on: ubuntu-lates
    environment: test_workflow
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Generate report
      id: generate-report
      run: |
        report_url=${{env.REPO}}
        echo "REPORT_URL=$report_url" >> $GITHUB_OUTPUT
    - name: Echo Output
      run: |
        echo "Generated report at ${{steps.generate-report.outputs.REPORT_URL}}"

        
