name: Get new file
run-name: get_new_file_${{inputs.machine_name}}_${{github.actor}}_${{github.run_id}}

on:
  push:
    branches: 
      report

jobs:
  get_workflow_result:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Get new files
      id: new-run-file
      run: |
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
        NEW_FILES=$(echo "$CHANGED_FILES" | grep "run_data")
        echo "NEW_FILES=$NEW_FILES" >> $GITHUB_ENV
    - name: Echo Output
      run: |
        echo "Switch state: ${{steps.new-run-file.outputs.NEW_FILES}}" >> $GITHUB_STEP_SUMMARY
